name: config_action
description: to print the configuration
inputs:
  build_artifacts:
    description: 'to build artifacts'
    required: false
    type: boolean
    default: false
  print_config:
    description: 'to print config'
    required: true
    type: boolean
    default: false

runs:
  if: ${{ inputs.print_config }}
  runs-on: ubuntu-latest
  steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
  
    - name: build_artifacts variables
      env:
        BUILD_ARTIFACTS: ${{ inputs.build_artifacts }}
      run: echo the build_artifacts is set to $BUILD_ARTIFACTS
