name: config_action
description: reusable workfl;ow in actions folder

inputs:
  build_artifacts:
    description: 'to build artifacts'
    required: false
    type: boolean
    default: false
  print_config:
    description: 'to print config'
    required: true
    type: boolean
    default: false

runs:
  using: composite
  shell: bash
  steps:
    - name: Print build_artifacts variable
      env:
        BUILD_ARTIFACTS: ${{ inputs.build_artifacts }}
      run: |
        echo "the build_artifacts is set to $BUILD_ARTIFACTS"
