name: Common Workflow

on:
  workflow_call:
    inputs:
      example-input:
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print input
        run: echo ${{ inputs.example-input }}
