name: .NET Core Build and Test

on:
  pull_request:
    branches: ["main"]
  
  workflow_dispatch:
    inputs:
      dotnet_version:
        description: '.NET version'
        required: true
        type: string
        default: '9.0'
      build_artifacts:
        description: 'to build artifacts'
        required: false
        type: boolean
        default: false
      print_config:
        description: 'to print config'
        required: true
        type: boolean
        default: false
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2   
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet_version }} 

    - name: dotnet version
      run: echo dotnet version ${{ inputs.dotnet_version }}
    - name: Restore dependencies for mainapp
      run: dotnet restore MainApplication/MainApplication/MainApplication.csproj 

    - name: Restore dependencies for mainapp.tests
      run: dotnet restore MainApplication/MainApplication.Tests/MainApplication.Tests.csproj 
      
    - name: Build the mainapp project
      run: dotnet build MainApplication/MainApplication/MainApplication.csproj  

    - name: Build the MainApplication.tests project
      run: dotnet build MainApplication/MainApplication.Tests/MainApplication.Tests.csproj 
 
    - name: Run tests for MainApplication.tests
      run: dotnet test MainApplication/MainApplication.Tests/MainApplication.Tests.csproj   

      
  print_configs:
    if: ${{ inputs.print_config }}
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: build_artifacts variables
        env:
          BUILD_ARTIFACTS: ${{ inputs.build_artifacts }}
        run: echo the build_artifacts is set to $BUILD_ARTIFACTS

   
