name: .NET Core Build and Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Check out repository
      uses: actions/checkout@v2   # Check out the code from the repository

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Specify the .NET version you're using

    - name: Restore dependencies for mainapp
      run: dotnet restore MainApplication/MainApplication/MainApplication.csproj  # Restore dependencies for the main application

    - name: Restore dependencies for mainapp.tests
      run: dotnet restore MainApplication/MainApplication.tests/MainApplication.tests.csproj  # Restore dependencies for the test project

    - name: Build the mainapp project
      run: dotnet build MainApplication/MainApplication/MainApplication.csproj --configuration Release  # Build the application project in Release mode

    - name: Build the MainApplication.tests project
      run: dotnet build MainApplication/MainApplication.tests/MainApplication.tests.csproj --configuration Release  # Build the test project

    - name: Run tests for MainApplication.tests
      run: dotnet test MainApplication/MainApplication.tests/MainApplication.tests.csproj --configuration Release  # Run tests for the test project

    - name: Publish test results
      if: always()  # This ensures that the test results are published even if the tests fail
      run: |
        mkdir -p test-results
        dotnet test main/mainapp.tests/mainapp.tests.csproj --configuration Release --logger "xunit;LogFileName=test-results.xml"
        mv test-results.xml test-results/
      
   
