name: .NET Core Build and Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2   
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0' 

    - name: Restore dependencies for mainapp
      run: dotnet restore MainApplication/MainApplication/MainApplication.csproj 

    - name: Restore dependencies for mainapp.tests
      run: dotnet restore MainApplication/MainApplication.Tests/MainApplication.Tests.csproj 
      
    - name: Build the mainapp project
      run: dotnet build MainApplication/MainApplication/MainApplication.csproj --configuration Release  

    - name: Build the MainApplication.tests project
      run: dotnet build MainApplication/MainApplication.Tests/MainApplication.Tests.csproj --configuration Release 

    - name: Run tests for MainApplication.tests
      run: dotnet test MainApplication/MainApplication.Tests/MainApplication.Tests.csproj --configuration Release

   
