name: .NET Core Build and Test

on:
  # push:
  #   branches:
  #     - main     
  # pull_request:
  #   branches:
  #     - main    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v2   

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build the project
      run: dotnet build --configuration Release  

    - name: Run tests
      run: dotnet test --configuration Release 

    - name: Run tests for MainApplication.Tests
      run: |
        mkdir -p test-results
        dotnet test MainApplication/MainApplication.Tests/MainApplication.Tests.csproj --configuration Release --logger "xunit;LogFileName=test-results.xml"
        mv test-results.xml test-results/
      
    - name: Upload test results to GitHub
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/test-results.xml  
