name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-common-workflow:
    uses: ./.github/workflows/common-workflow.yml
    with:
      example-input: 'some-value' 
