name: new_config_action
on:
  workflow_call:
    inputs:
      build_artifacts:
        description: 'to build artifacts'
        required: false
        type: boolean
        default: false
      print_config:
        description: 'to print config'
        required: true
        type: boolean
        default: false

jobs:
  print_config_job: 
    if: ${{ inputs.print_config }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Print event context
        run: |
          echo "${{ toJson(github.event) }}"
    
      - name: Print build_artifacts variable
        env:
          BUILD_ARTIFACTS: ${{ inputs.build_artifacts }}
        run: |
          echo "the build_artifacts is set to $BUILD_ARTIFACTS"
